language: cpp

# This will run on Travis' 'new' container-based infrastructure
sudo: false

# only run it for opensource
branches:
  only:
    - opensource

# Environment variables
env:
  global:
    - GH_REPO_NAME: EVAA
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/DrStS/EVAA.git
      
# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# random function for success
script:
  - echo "test"

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh