name: Build documentation

on: [workflow_dispatch]
jobs:
  buildDocumentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          ref: 'refactoring/codeStripping'
    - name: Add exec bit
      run : chmod +x rundocker.sh
      working-directory: ./doc/LaTeX
    - name: Run LaTeX in Docker
      run: ls -a
      run: ./rundocker.sh latexmk -pdf -interaction=nonstopmode -halt-on-error EVAADocumentation.tex
      working-directory: ./doc/LaTeX
      shell: bash
