name: Build Doxygen doc

on: [push, workflow_dispatch]
jobs:
  buildDoxygenDocumentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          ref: 'refactoring/codeStripping'
    - name: Run Doxygen
      uses: mattnotmitt/doxygen-action@v1
      with:
        doxyfile-path: ./doc/Doxyfile
    - name: Run ls
      run : ls -a 
      working-directory: ./doc
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN_EVAA }}
        publish_dir: ./html
        
    - name: Trigger LaTeX documentation
      if: ${{ success()}}
      uses: benc-uk/workflow-dispatch@v1
      with:   
        workflow: Build LaTeX doc
        ref: refactoring/codeStripping  
        token: ${{ secrets.PERSONAL_TOKEN_EVAA }}