
name: Build LaTeX doc

on: [push, workflow_dispatch]
jobs:
  buildLaTeXDocumentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          ref: 'refactoring/codeStripping'
    - name: Add exec bit
      run : chmod +x rundocker.sh
      working-directory: ./doc/LaTeX
    - name: Run LaTeX in Docker
      run: ./rundocker.sh latexmk -pdf -interaction=nonstopmode -halt-on-error EVAADocumentation.tex
      working-directory: ./doc/LaTeX
      shell: bash
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: EVAADocumentation.pdf
        path: ./doc/LaTeX/EVAADocumentation.pdf
      
    
      
