name: Build Doxygen documentation

on: [workflow_dispatch,push]
jobs:
  buildDoxygenDocumentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          ref: 'refactoring/codeStripping'
    - name: Run Doxygen
      uses: mattnotmitt/doxygen-action@v1
      with:
        doxyfile-path: ./doc/Doxygen
    
      
